using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Omid.Developer
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.ReadKey();
            Console.Clear();
            Console.ForegroundColor = ConsoleColor.Green;
            Console.WriteLine("Omid.Developer");
            Console.ForegroundColor = ConsoleColor.White;
            Console.WriteLine("Beep Music");
            Console.ForegroundColor = ConsoleColor.Red;
            Console.WriteLine("Start Beep Music By Omid.Developer");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.Beep(500, 500);
            Console.Beep(1000, 500);
            Console.Beep(500, 500);
            Console.Beep(1000, 500);
            Console.Beep(500, 500);
            Console.Beep(1000, 500);
            Console.Beep(10000, 1000);
            Console.Beep(500, 500);
            Console.Beep(1000, 500);
            Console.Beep(500, 500);
            Console.Beep(1000, 500);
            Console.Beep(500, 500);
            Console.Beep(1000, 500);
            Console.Beep(10000, 1000);
            Console.Beep(500, 500);
            Console.Beep(1000, 500);
            Console.Beep(500, 500);
            Console.Beep(1000, 500);
            Console.Beep(500, 500);
            Console.Beep(1000, 500);
            Console.Beep(10000, 3000);
            Console.ForegroundColor = ConsoleColor.Cyan;
            Console.WriteLine("Visit My Web : www.Iran-Download.net");
                Console.Beep(3000, 600);
                Console.Beep(1500, 300);
                Console.Beep(3000, 600);
                Console.Beep(1500, 300);
                Console.Beep(3000, 600);
                Console.Beep(1500, 300);
                Console.Beep(3000, 600);
                Console.Beep(1500, 300);
                Console.Beep(3000, 600);
                Console.Beep(1500, 300);
                Console.Beep(3000, 600);
                Console.Beep(1500, 300);
                Console.Beep(3000, 600);
                Console.Beep(1500, 300);
                Console.Beep(3000, 600);
                Console.Beep(1500, 300);
                Console.Beep(3000, 600);
                Console.Beep(1500, 300);
                Console.Beep(10000, 3000);
                Console.Beep(3333, 600);
                Console.Beep(1111, 300);
                Console.Beep(3333, 600);
                Console.Beep(1111, 300);
                Console.Beep(3333, 600);
                Console.Beep(1111, 300);
                Console.Beep(3333, 600);
                Console.Beep(1111, 300);
                Console.Beep(3333, 600);
                Console.Beep(1111, 300);
                Console.Beep(3333, 600);
                Console.Beep(1111, 300);
                Console.Beep(3333, 600);
                Console.Beep(1111, 300);
                Console.Beep(3333, 600);
                Console.Beep(1111, 300);
                Console.Beep(3333, 600);
                Console.Beep(1111, 300);
                Console.Beep(10000, 3000);
                Console.Beep(100, 300);
                Console.Beep(500, 100);
                Console.Beep(100, 300);
                Console.Beep(500, 100);
                Console.Beep(100, 300);
                Console.Beep(500, 100);
                Console.Beep(100, 300);
                Console.Beep(500, 100);
                Console.Beep(100, 300);
                Console.Beep(500, 100);
                Console.Beep(100, 300);
                Console.Beep(500, 100);
                Console.Beep(100, 300);
                Console.Beep(500, 100);
                Console.Beep(100, 300);
                Console.Beep(500, 100);
                Console.Beep(100, 300);
                Console.Beep(500, 100);
                Console.Beep(100, 300);
                Console.Beep(500, 100);
        }
    }
}
